name: Release (Tag Push)

on:
  push:
    tags:
      - '**'
  workflow_dispatch: # Permite disparo manual também

jobs:
  release-to-remote:
    name: Sync Release to Remote Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - id: extract-package
        run: |
          TAG_REF="${GITHUB_REF}"
          echo "Tag reference: $TAG_REF"

          TAG_NAME="${TAG_REF#refs/tags/}"
          echo "Tag name: $TAG_NAME"

          # check if tag name meets the format 'lacus/<package-name>@<version>'
          if [[ "$TAG_NAME" == lacus/*@* ]]; then
            PACKAGE_NAME=${TAG_NAME#lacus/*}
            PACKAGE_NAME=${PACKAGE_NAME%@*}
            echo "Package name: $PACKAGE_NAME"

            VERSION=${TAG_NAME#*$PACKAGE_NAME@}
            echo "Version: $VERSION"
          else
            echo "❌ Tag name does not match the expected format: 'lacus/<package-name>@<version>'"
            exit 1
          fi

          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "package_version=v$VERSION" >> $GITHUB_OUTPUT
          echo "package_url=git@github.com:LacusSolutions/br-utils-php_${PACKAGE_NAME}.git" >> $GITHUB_OUTPUT

      - id: check-remote-exists
        run: |
          REMOTE_URL="${{ steps.extract-package.outputs.package_url }}"

          if ! git ls-remote "$REMOTE_URL" &> /dev/null; then
            echo "❌ Remote repository not found: $REMOTE_URL"
            exit 1
          fi

          echo "✅ Remote repository exists."

      - run: |
          REMOTE_URL="${{ steps.extract-package.outputs.package_url }}"
          PACKAGE_VERSION="${{ steps.extract-package.outputs.package_version }}"
          TAG_NAME="$PACKAGE_VERSION"

          git tag -f $TAG_NAME
          git push $REMOTE_URL $TAG_NAME
          echo "✅ Tag pushed to remote repository."
