name: Release

on:
  release:
    types: ['published']
  workflow_dispatch: # Allow manual triggering

jobs:
  release-to-remote:
    name: Sync Release to Remote Repository
    runs-on: ubuntu-latest
    if: endsWith(github.event.release.target_commitish, '/main')
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - id: extract-package
        run: |
          PACKAGE_NAME=$(echo "${{ github.event.release.target_commitish }}" | sed 's|/main$||')

          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "package_url=git@github.com:LacusSolutions/br-utils-php_$PACKAGE_NAME.git" >> $GITHUB_OUTPUT
          echo "Extracted package name: $PACKAGE_NAME"

      - id: check-remote-exists
        run: |
          REMOTE_URL="${{ steps.extract-package.outputs.package_url }}"

          if ! git ls-remote $REMOTE_URL; then
            echo "Remote repository does not exist"
            exit 1
          fi

      - run: |
          REMOTE_URL="${{ steps.extract-package.outputs.package_url }}"

          git remote add remote-repo $REMOTE_URL
          git push remote-repo --tags
